version: '3.8'

services:
  elasticsearch:
    image: "elasticsearch:8.7.0"
    container_name: elastic-search
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    networks:
      - log-network

  kibana:
    image: "kibana:8.7.0"
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    ports:
      - "5601:5601"
    networks:
      - log-network

  logstash:
    image: "logstash:8.7.0"
    container_name: logstash
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    networks:
      - log-network

networks:
  log-network:
    driver: bridge